### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by aniruddhpatel28** [php-kchat/kchat#1]

**Comment by GaneshKandu** [comment]
**Could you Please provide me more details…**

**Comment by aniruddhpatel28** [comment]
after installation, when i try to login it gives "HTTP ERROR 500"

**Comment by GaneshKandu** [comment]
Can you show me error log file **logs/kchat.log.php**

**Comment by ivysashar** [comment]
Hi, after installing kchat on my wordpress site, and embedding the code, I was not able to see the livechat icon on my home page. Please help...

**Comment by GaneshKandu** [comment]
@ivysashar did you added jquery ? , add this too
```js
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="[[url]]/box/assets/js/kchat.js"></script>
```
```html
<script>
  data = {
    'url': '[[URL]]/box/',
    'key': '[[YOUR KEY]]'
  };
  kbox.init(data);
</script>
```
**Sorry !** not added in documentation for jquery.
