### ISSUE TITLE
Close button for chat window

### ISSUE THREAD

**Issue by vaidyamanishjoshi** [php-kchat/kchat#10]
To help us resolve your issue more quickly, please use the following template:

## Version Info
  - KChat version: 1.0.9
  - PHP version:  7.3
  - MySQL version: 10.1.37 Maria DB
  - Web server (Ex. Apache, nginx or IIS?) :Apache
  - OS name and version: linux

## Expected Behavior

Close button not visible in opened chat window at frontend

Name, Email Message fields should not be empty...

## Actual Behavior

Close button not visible in opened chat window at frontend

Empty Name , Email and message sent . no validation for empty inputs in frontend.

## Steps to Reproduce

> Write here

## Error Log

> Upload ```logs/kchat.log.php``` file

**Comment by GaneshKandu** [comment]
@vaidyamanishjoshi 
please update to 1.0.10 for requested features .

**Comment by GaneshKandu** [comment]
Closing
