### ISSUE TITLE
Not load

### ISSUE THREAD

**Issue by Gadgetroch** [php-kchat/kchat#2]
Hi,

When i configure database by the web interface, it does'nt load after submit.

Someone can help ?

**Comment by GaneshKandu** [comment]
Hi @Gadgetroch 
what error are you getting ?
Please show me your error log ```logs/kchat.log.php``` file

**Comment by Gadgetroch** [comment]
php -S 192.168.1.201:8080 -t kchat              
PHP 7.0.33-0+deb9u1 Development Server started at Fri Jan  4 21:21:27 2019
Listening on http://192.168.1.201:8080
Document root is /opt/kchat
Press Ctrl-C to quit.
[Fri Jan  4 21:21:30 2019] 192.168.1.11:58016 [500]: /p/ - Uncaught Error: Call to undefined function apache_get_modules() in /opt/kchat/kchat/ctrl/login.php:48
Stack trace:
#0 /opt/kchat/kchat/lib/route.php(141): login->index(Array)
#1 /opt/kchat/kchat/lib/init.php(39): require_once('/opt/kchat/kcha...')
#2 /opt/kchat/vendor/composer/autoload_real.php(66): require('/opt/kchat/kcha...')
#3 /opt/kchat/vendor/composer/autoload_real.php(56): composerRequire0d647e022149540ae7f7f02c0b724e3f('08eadcb7512b347...', '/opt/kchat/vend...')
#4 /opt/kchat/vendor/autoload.php(7): ComposerAutoloaderInit0d647e022149540ae7f7f02c0b724e3f::getLoader()
#5 /opt/kchat/index.php(3): require_once('/opt/kchat/vend...')
#6 {main}
  thrown in /opt/kchat/kchat/ctrl/login.php on line 48

**Comment by GaneshKandu** [comment]
Hi @Gadgetroch 

Download [https://github.com/php-kchat/kchat/archive/master.zip](https://github.com/php-kchat/kchat/archive/master.zip)

it should work now

**Comment by Gadgetroch** [comment]
![image](https://user-images.githubusercontent.com/46190566/50723179-7f875000-10da-11e9-807c-fc786d60731b.png)

I stay here, no way to go next

`/opt/ cat kchat/logs/kchat.log.php`
`<?php die(); ?>#`

**Comment by GaneshKandu** [comment]
HI @Gadgetroch 

Please Remove port number from host ip of mysql server or use localhost if mysql server is on same machine

please let me know if works
