### ISSUE TITLE
install issue - key generation fails

### ISSUE THREAD

**Issue by JustinWebDev** [php-kchat/kchat#28]
To help us resolve your issue more quickly, please use the following template:

## Version Info
  - KChat version: ``` latest ```
  - PHP version:  ``` 8.1 ```
  - MySQL version:  ``` 8 ```
  - Web server (Ex. Apache, nginx or IIS?) : ``` ? ```
  - OS name and version:  ``` Mint 21 ```

## Expected Behavior
key generation works

## Actual Behavior
key generation fails with /kchat/vendor/autoload.php - no such file in /kchat/artisan on line 18
**vendor folder does not exist**

## Steps to Reproduce
install with: composer create-project php-kchat/kchat
edit .env file
run: php artisan key:generate

**Comment by GaneshKandu** [comment]
Look like ``composer create-project php-kchat/kchat`` was not successful.
delete and try again installing

or just delete ``vendor`` folder and ``composer.lock`` file and run ``composer install``

**Comment by JustinWebDev** [comment]
Well, I can't delete the vendor folder because the problem is the vendor folder is missing.

I started over and used composer install.  Thanks.
