### ISSUE TITLE
Stuck at database settings when running with docker

### ISSUE THREAD

**Issue by idzharbae** [php-kchat/kchat#3]
Your application works fine when i run it on my own pc with php -S command. But when I tried to run it with docker it got stuck at database settings page. the kchat.log.php shows nothing.
When I clicked on "Continue" button this message shows up on javascript console : 

`Object { database: "defaultdb", username: "root", password: "secret", host: "localhost", port: "13306", dbprefix: "kcgs_" }
kchat.js:386:2
error kchat.js:408:4 `

I have no idea what went wrong because the error message shows nothing.

Here is the content my docker-compose.yml file : 

`version: '3'
services:
    php-apache:
        build:
            context: ./php-apache
        ports:
            - 8000:80
        volumes:
            - ./DocumentRoot:/var/www/html
            - ./phpconfig:/usr/local/etc/php
        links:
            - 'mariadb'
    mariadb:
        image: mariadb:10.1
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: 'Asia/Jakarta'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'defaultdb'
        ports:
            - 13306:3306

volumes:
    mariadb:`

php-apache/Dockerfile : 
`FROM php:7.2.1-apache
RUN docker-php-ext-install pdo pdo_mysql mysqli`

**Comment by GaneshKandu** [comment]
is ```config.php``` and ```db.php``` created in ```config``` folder ?
check if 13 database created in your database server

**Comment by idzharbae** [comment]
There was only config.php in the config folder and the database was empty

**Comment by idzharbae** [comment]
I think I found the error, should've use the database container name instead of localhost... Thanks for responding btw
