### ISSUE TITLE
MySql 8

### ISSUE THREAD

**Issue by alimo2** [php-kchat/kchat#33]
Hi

Is there any problem with MySql 8 ?

` could not find driver (SQL: select * from information_schema.tables where table_schema = laravel and table_name = migrations and table_type = 'BASE TABLE')
`

**Comment by GaneshKandu** [comment]
it works on MySql 8 ?

**Comment by alimo2** [comment]
> it works on MySql 8 ?

Yes this is my question.

**Comment by alimo2** [comment]
Yes it works well. this was my mistake. tnx
