### ISSUE TITLE
Does the chat software only work if you have your own root rights?

### ISSUE THREAD

**Issue by VDelport** [php-kchat/kchat#5]
Does the chat software only work if you have your own root rights, or can you also use it if you install it on a web space without root rights?

When I run KChat on localhost, the chat works fine. When I try to start KChat on a webspace without root rights, I get the message:
"Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at ... to inform them of the time this error occurred, and the actions you performed just before this error. More information about this error may be available in the server error log. "

**Comment by GaneshKandu** [comment]
HI,

Can you tell me what error is in the file ``logs/kchat.log.php``

**Comment by VDelport** [comment]
Thank you for your question. After a few more tests, I think that the problem is not caused by KChat, but that the web space I want to run KChat on doesn't give me enough rights. As I said, in my development environment, i.e. on localhost, KChat runs satisfactorily. You can therefore close the issue. Best regards.

**Comment by GaneshKandu** [comment]
Glad to know, Thanks.
