### ISSUE TITLE
https not working

### ISSUE THREAD

**Issue by yigitkeremoktay** [php-kchat/kchat#8]
To help us resolve your issue more quickly, please use the following template:

## Version Info
  - KChat version: ``` latest as of now ```
  - PHP version:  ``` 7.3 ```
  - MySQL version:  ``` 5.7 ```
  - Web server (Ex. Apache, nginx or IIS?) : ``` Apache ```
  - OS name and version:  ``` Ubuntu ```

## Expected Behavior

> Site should load over https

## Actual Behavior

> Site loads but css files are missing

## Steps to Reproduce

> Install normally and load over https

## Error Log

> Upload ```logs/kchat.log.php``` file

**Comment by GaneshKandu** [comment]
@yigitkeremoktay 

if you install on ```https``` it will work
if you installed on ```https``` and moved on ```https``` it will not work

delete ```config/config.php``` and refresh you page with ```https``` in url should work

**Comment by yigitkeremoktay** [comment]
OK. Thanks!

**Comment by GaneshKandu** [comment]
@yigitkeremoktay 

if you install on ```https``` it will work
if you installed on ```http``` and moved on ```https``` it will not work

delete ```config/config.php``` and refresh your page with ```https``` in url should work
